### ISSUE TITLE
Uncaught linking error

### ISSUE THREAD

**Issue by lollogiro** [mybeon/react-native-schedule-exact-alarm-permission#2]
After installing the package following the documentation I encountered this error:
```
ERROR  Error: The package 'react-native-schedule-exact-alarm-permission' doesn't seem to be linked. Make sure:

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes
```

I'm using Expo Go SDK 51
Client version 2.31.2

Has anyone else encountered this error?

**Comment by beonma** [comment]
Hi @lollogiro , unfortunately you will need to use bare React Native, as this package does not support Expo Go. If this feature is essential to your app, you might need to consider ejecting your app or waiting until Expo Go provides a way to request the schedule-exact-alarm permission.

**Comment by lollogiro** [comment]
> Hi @lollogiro , unfortunately you will need to use bare React Native, as this package does not support Expo Go. If this feature is essential to your app, you might need to consider ejecting your app or waiting until Expo Go provides a way to request the schedule-exact-alarm permission.

Thank you!
